version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      FLASK_ENV: development
    depends_on:
      - prometheus
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring_network

volumes:
  grafana-storage:

networks:
  monitoring_network:
    driver: bridge
